import logging

_logger = logging.getLogger(__name__)

ATTRIBUTE_FIELD_MAP: dict[str, str] = {
    # Odoo field -> API attribute name
    # Integers
    "rooms": "rooms",
    "floor": "floor",
    "floors_total": "total_floors",
    "year_built": "year_built",
    "entrance": "entrance",
    "bedrooms": "bedrooms",
    "bathroom_count": "bathroom_count",
    "parking_count": "parking_count",
    "electricity_power": "electricity_power",
    # Decimals
    "area_total": "area",
    "area_kitchen": "kitchen_area",
    "area_living": "living_area",
    "ceiling_height": "ceiling_height",
    "area_land": "area_land",
    "area_commercial": "area_commercial",
    "area_warehouse": "area_warehouse",
    # Enums (value_text)
    "building_type": "building_type",
    "condition": "condition",
    "bathroom": "bathroom",
    "balcony": "balcony",
    "parking": "parking",
    "furniture": "furniture",
    "internet": "internet",
    "heating": "heating_type",
    "gas": "gas",
    "water": "water",
    "sewage": "sewage",
    "electricity": "electricity",
    "wall_material": "wall_material",
    "foundation": "foundation",
    "roof_type": "roof_type",
    "window_type": "window_type",
    "commercial_type": "commercial_type",
    "road_access": "road_access",
    "ownership_type": "ownership_type",
    "land_category": "land_category",
    "land_status": "land_status",
    # Booleans
    "balcony_glazed": "balcony_glazed",
    "isolated_rooms": "isolated_rooms",
    "storage": "storage",
    "quiet_yard": "quiet_yard",
    "kitchen_studio": "kitchen_studio",
    "new_plumbing": "new_plumbing",
    "built_in_kitchen": "built_in_kitchen",
    "security_intercom": "security_intercom",
    "security_video": "security_video",
    "security_alarm": "security_alarm",
    "security_fire_alarm": "security_fire_alarm",
    "security_coded_lock": "security_coded_lock",
    "security_concierge": "security_concierge",
    "is_pledged": "is_pledged",
    "is_privatized": "is_privatized",
    "documents_ready": "documents_ready",
    "encumbrance": "encumbrance",
    "communications_nearby": "communications_nearby",
    "has_showcase": "has_showcase",
    "separate_entrance": "separate_entrance",
    # Inverted boolean
    "not_corner": "is_corner",
}
