from . import (
    crm_lead,
    estate_appliance,
    estate_city,
    estate_climate_equipment,
    estate_district,
    estate_property,
    estate_property_image,
    estate_property_webhook_mixin,
    estate_source,
    estate_street,
    estatekit_webhook_event,
    res_config_settings,
    res_partner,
    res_users,
)
