from typing import Protocol


class IImageServiceGateway(Protocol):
    def upload(self, data: bytes, content_type: str, generate_thumbnail: bool) -> dict | None: ...

    def download(self, key: str) -> tuple[bytes, str] | None: ...

    def delete(self, key: str) -> bool: ...

    def delete_many(self, keys: list[str]) -> list[bool]: ...

    def rotate(self, key: str, degrees: int) -> dict | None: ...

    def upload_video(self, data: bytes, content_type: str, generate_poster: bool) -> dict | None: ...

    def download_video(self, key: str) -> tuple[bytes, str] | None: ...

    def get_video_url(self, key: str, expires_in_seconds: int = 3600) -> str | None: ...

    def delete_video(self, key: str) -> bool: ...
