site_name: EstateKit CRM — Техническая документация
site_url: https://crm-docs.estate-kit.com/

extra_javascript:
  - javascripts/logout.js
use_directory_urls: true
theme:
  name: material
  language: ru
  palette:
    scheme: default
    primary: deep-purple

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables

nav:
  - Главная: index.md
  - Модель данных: data-model.md
  - Атрибуты: attributes.md
  - Интеграции: integrations.md
  - WhatsApp: whatsapp.md
  - Комиссия: commissions.md
