from typing import Protocol


class IImageServiceGateway(Protocol):
    def upload(self, data: bytes, content_type: str, generate_thumbnail: bool) -> dict | None: ...

    def download(self, key: str) -> tuple[bytes, str] | None: ...

    def delete(self, key: str) -> bool: ...

    def delete_many(self, keys: list[str]) -> list[bool]: ...
