from collections.abc import Callable
from typing import Any

class Environment:
    cr: Any
    uid: int
    context: dict[str, Any]
    def __getitem__(self, model_name: str) -> Any: ...

def model(method: Callable[..., Any]) -> Callable[..., Any]: ...
def depends(*args: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def depends_context(*args: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def onchange(*args: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def constrains(*args: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def ondelete(**kwargs: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def returns(model: str, downgrade: Callable[..., Any] | None = None, upgrade: Callable[..., Any] | None = None) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def autovacuum(method: Callable[..., Any]) -> Callable[..., Any]: ...
def model_create_multi(method: Callable[..., Any]) -> Callable[..., Any]: ...
