class UserError(Exception):
    def __init__(self, message: str) -> None: ...

class ValidationError(Exception):
    def __init__(self, message: str) -> None: ...

class AccessError(Exception):
    def __init__(self, message: str) -> None: ...

class MissingError(Exception):
    def __init__(self, message: str) -> None: ...

class AccessDenied(Exception):
    def __init__(self, message: str = ...) -> None: ...

class RedirectWarning(Exception):
    def __init__(self, message: str, action: int, button_text: str) -> None: ...

class CacheMiss(Exception): ...
