from typing import Any

class Field:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Boolean(Field): ...
class Integer(Field): ...
class Float(Field): ...
class Monetary(Field): ...
class Char(Field): ...
class Text(Field): ...
class Html(Field): ...
class Date(Field):
    @staticmethod
    def today() -> Any: ...
    @staticmethod
    def context_today(record: Any) -> Any: ...
    @staticmethod
    def to_date(value: Any) -> Any: ...
    @staticmethod
    def to_string(value: Any) -> str: ...

class Datetime(Field):
    @staticmethod
    def now() -> Any: ...
    @staticmethod
    def today() -> Any: ...
    @staticmethod
    def context_timestamp(record: Any, timestamp: Any) -> Any: ...
    @staticmethod
    def to_datetime(value: Any) -> Any: ...
    @staticmethod
    def to_string(value: Any) -> str: ...

class Binary(Field): ...
class Image(Field): ...
class Selection(Field): ...
class Reference(Field): ...

class Many2one(Field):
    id: int
    ids: list[int]
    name: str
    def __getattr__(self, name: str) -> Any: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Any: ...

class One2many(Field):
    def __getattr__(self, name: str) -> Any: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __or__(self, other: Any) -> Any: ...

class Many2many(Field):
    def __getattr__(self, name: str) -> Any: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
class Json(Field): ...
class Properties(Field): ...
class PropertiesDefinition(Field): ...

class Command:
    @staticmethod
    def create(values: dict[str, Any]) -> tuple[int, int, dict[str, Any]]: ...
    @staticmethod
    def update(id: int, values: dict[str, Any]) -> tuple[int, int, dict[str, Any]]: ...
    @staticmethod
    def delete(id: int) -> tuple[int, int, int]: ...
    @staticmethod
    def unlink(id: int) -> tuple[int, int, int]: ...
    @staticmethod
    def link(id: int) -> tuple[int, int, int]: ...
    @staticmethod
    def clear() -> tuple[int, int, int]: ...
    @staticmethod
    def set(ids: list[int]) -> tuple[int, int, list[int]]: ...
