from typing import Any, Self

class BaseModel:
    _name: str
    _description: str
    _inherit: str | list[str]
    _inherits: dict[str, str]
    _order: str
    _rec_name: str
    _table: str
    _sql_constraints: list[tuple[str, str, str]]

    id: int
    env: Environment
    ids: list[int]

    def create(self, vals: dict[str, Any]) -> Self: ...
    def write(self, vals: dict[str, Any]) -> bool: ...
    def unlink(self) -> bool: ...
    def read(self, fields: list[str] | None = None) -> list[dict[str, Any]]: ...
    def search(self, domain: list[Any], offset: int = 0, limit: int | None = None, order: str | None = None) -> Self: ...
    def search_count(self, domain: list[Any]) -> int: ...
    def browse(self, ids: int | list[int]) -> Self: ...
    def exists(self) -> Self: ...
    def filtered(self, func: Any) -> Self: ...
    def mapped(self, func: Any) -> Any: ...
    def sorted(self, key: Any = None, reverse: bool = False) -> Self: ...
    def sudo(self, flag: bool = True) -> Self: ...
    def with_context(self, **kwargs: Any) -> Self: ...
    def with_user(self, user: Any) -> Self: ...
    def with_company(self, company: Any) -> Self: ...
    def ensure_one(self) -> Self: ...
    def name_get(self) -> list[tuple[int, str]]: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __or__(self, other: Self) -> Self: ...
    def __and__(self, other: Self) -> Self: ...
    def __sub__(self, other: Self) -> Self: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

class Model(BaseModel): ...
class TransientModel(BaseModel): ...
class AbstractModel(BaseModel): ...

class Environment:
    cr: Any
    uid: int
    context: dict[str, Any]
    company: Any
    companies: Any
    user: Any
    ref: Any
    def __getitem__(self, model_name: str) -> BaseModel: ...
