SELECTION_LABELS: dict[str, dict[str, str]] = {
    "property_type": {
        "apartment": "Квартира", "house": "Дом", "townhouse": "Таунхаус",
        "commercial": "Коммерция", "land": "Земля",
    },
    "deal_type": {
        "sale": "Продажа", "rent_long": "Долгосрочная аренда",
        "rent_daily": "Посуточная аренда",
    },
    "condition": {
        "no_repair": "Без ремонта", "cosmetic": "Косметический",
        "euro": "Евроремонт", "designer": "Дизайнерский",
    },
    "building_type": {
        "panel": "Панельный", "brick": "Кирпичный", "monolith": "Монолит",
        "metal_frame": "Металлокаркас", "wood": "Деревянный",
    },
    "wall_material": {
        "brick": "Кирпич", "gas_block": "Газоблок", "wood": "Дерево",
        "sip": "СИП-панели", "frame": "Каркас", "polystyrene": "Полистиролбетон",
    },
    "roof_type": {"flat": "Плоская", "gable": "Двускатная", "hip": "Вальмовая"},
    "foundation": {"strip": "Ленточный", "slab": "Плитный", "pile": "Свайный"},
    "bathroom": {"combined": "Совмещённый", "separate": "Раздельный"},
    "balcony": {
        "none": "Нет", "balcony": "Балкон", "loggia": "Лоджия", "terrace": "Терраса",
    },
    "parking": {
        "none": "Нет", "yard": "Двор", "underground": "Подземная",
        "garage": "Гараж", "ground": "Наземная",
    },
    "furniture": {"none": "Без мебели", "partial": "Частично", "full": "Полная"},
    "heating": {"central": "Центральное", "autonomous": "Автономное", "none": "Нет"},
    "water": {"central": "Центральное", "well": "Скважина", "none": "Нет"},
    "sewage": {"central": "Центральная", "septic": "Септик", "none": "Нет"},
    "gas": {"central": "Центральный", "balloon": "Баллонный", "none": "Нет"},
    "electricity": {"yes": "Есть", "nearby": "Рядом", "none": "Нет"},
    "commercial_type": {
        "office": "Офис", "retail": "Торговое", "warehouse": "Склад",
        "production": "Производство",
    },
    "land_category": {
        "izhs": "ИЖС", "snt": "СНТ", "lpkh": "ЛПХ", "commercial": "Коммерческое",
    },
    "land_status": {"owned": "В собственности", "leased": "Аренда"},
    "road_access": {
        "asphalt": "Асфальт", "gravel": "Гравий", "dirt": "Грунтовая", "none": "Нет",
    },
}

# (field_name, label, optional) — optional=True значит необязательное поле
_COMMON_FIELDS: list[tuple[str, str, bool]] = [
    ("property_type", "Тип", False),
    ("deal_type", "Тип сделки", False),
    ("price", "Цена (за весь объект)", False),
    ("price_per_sqm", "Цена за м²", False),
    ("currency", "Валюта", False),
    ("area_total", "Общая площадь (м²)", False),
    ("city", "Город", False),
    ("district", "Район", False),
    ("year_built", "Год постройки", True),
    ("description", "Описание", True),
    ("photo_count", "Количество фото", False),
    ("parking", "Парковка", True),
    ("heating", "Отопление", True),
]

PROPERTY_TYPE_FIELDS: dict[str, list[tuple[str, str, bool]]] = {
    "apartment": [
        ("rooms", "Комнат", False),
        ("bedrooms", "Спален", True),
        ("floor", "Этаж", False),
        ("floors_total", "Этажность", False),
        ("building_type", "Тип строения", True),
        ("ceiling_height", "Высота потолков (м)", True),
        ("area_living", "Жилая площадь (м²)", True),
        ("area_kitchen", "Площадь кухни (м²)", True),
        ("condition", "Состояние", False),
        ("bathroom", "Санузел", True),
        ("balcony", "Балкон", True),
        ("furniture", "Мебель", True),
        ("residential_complex", "ЖК (опц.)", True),
        ("internet", "Интернет", True),
    ],
    "house": [
        ("rooms", "Комнат", True),
        ("floors_total", "Этажность", True),
        ("area_living", "Жилая площадь (м²)", True),
        ("area_kitchen", "Площадь кухни (м²)", True),
        ("area_land", "Площадь участка (сотки)", False),
        ("wall_material", "Материал стен", True),
        ("roof_type", "Тип крыши", True),
        ("foundation", "Фундамент", True),
        ("condition", "Состояние", False),
        ("bathroom", "Санузел", True),
        ("furniture", "Мебель", True),
        ("water", "Водоснабжение", True),
        ("sewage", "Канализация", True),
        ("gas", "Газ", True),
        ("electricity", "Электричество", True),
    ],
    "townhouse": [
        ("rooms", "Комнат", True),
        ("floors_total", "Этажность", True),
        ("area_living", "Жилая площадь (м²)", True),
        ("area_land", "Площадь участка (сотки)", True),
        ("condition", "Состояние", False),
        ("wall_material", "Материал стен", True),
        ("bathroom", "Санузел", True),
        ("furniture", "Мебель", True),
        ("water", "Водоснабжение", True),
        ("sewage", "Канализация", True),
        ("gas", "Газ", True),
        ("electricity", "Электричество", True),
    ],
    "commercial": [
        ("commercial_type", "Назначение", False),
        ("floor", "Этаж", True),
        ("floors_total", "Этажность", True),
        ("area_commercial", "Торговая площадь (м²)", True),
        ("area_warehouse", "Складская площадь (м²)", True),
        ("ceiling_height", "Высота потолков (м)", True),
        ("condition", "Состояние", True),
        ("separate_entrance", "Отдельный вход", True),
        ("has_showcase", "Витрины", True),
        ("electricity_power", "Мощность электричества (кВт)", True),
        ("internet", "Интернет", True),
    ],
    "land": [
        ("area_land", "Площадь участка (сотки)", False),
        ("land_category", "Категория земли", False),
        ("land_status", "Статус земли", True),
        ("road_access", "Подъездная дорога", True),
        ("communications_nearby", "Коммуникации рядом", True),
        ("water", "Водоснабжение", True),
        ("sewage", "Канализация", True),
        ("gas", "Газ", True),
        ("electricity", "Электричество", True),
    ],
}
